name: Django CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.x]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r mysite/requirements.txt
    - name: Run Tests
      run: |
        python mysite/manage.py test

    
    - name: Login to Docker Hub
      uses: docker/login-action@v2 
      with:
        username: ${{ secrets.USR}}
        password: ${{ secrets.PWD }}
  
    - name: Build Docker image
      run: docker build -t ewuramaamponsah445/pyprojj1:latest .
    
    - name: Push Docker image to Docker Hub
      run: docker push ewuramaamponsah445/pyprojj1:latest
